config/routes.rb
Rails.application.routes.draw do
  resources :passengers, only: [:index]

  resources :trips, only: [:index] do
    resources :passengers
    member do
      get :book
    end
  end


  resources :user do
    resources :passengers, only: [:show] do
      member do
        get :add_extra_luggage
      end
    end
    resources :credit_cards
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #

  # Defines the root path route ("/")
  root "trips#index"
end

app/models/trip.rb
class Trip < ApplicationRecord

  # models/concerns/filterable.rb
  include Filterable

  belongs_to :departure, class_name: 'Location'
  belongs_to :arrival, class_name: 'Location'

  has_many :passengers
  has_many :users, through: :passengers

  # call this method in controller to filter trips
  scope :not_departed,             -> { where("departure_time >= ? ", DateTime.now) }
  scope :filter_by_departure,      -> (departure)       { where departure: departure }
  scope :filter_by_arrival,        -> (arrival)         { where arrival: arrival }
  scope :filter_by_departure_time, -> (departure_time)  { where("departure_time >= ? ", departure_time) }

  #
  scope :total_revenue_by_departure, -> { joins(:passengers).group(:departure).sum(:price) }

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[ show book ]

  before_action :authenticate_user!, :except => [:index]

  # GET /trips or /trips.json
  def index
    @trips = Trip.where(nil)
    # models/concerns/filterable.rb
    filtering_params(params).each do |key, value|
      @trips = @trips.public_send("filter_by_#{key}", value) if value.present?
    end
  end

  # GET /trips/1 or /trips/1.json
  def show
  end

  def book
    session[:trip_id] = nil if session[:trip_id]

    passenger = @trip.passengers.build(user_id: current_user.id, price: @trip.base_price)

    if passenger.save
      redirect_to(trip_passenger_url(@trip,passenger), notice: "Ticket was successfully bought.")
    else
      session[:trip_id] = @trip.id
      redirect_to new_user_credit_card_url(current_user), notice: passenger.errors.messages.values
    end
  end

  private

    # A list of the param names that can be used for filtering the Product list
    def filtering_params(params)
      params.slice(:departure, :arrival, :departure_time)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # def trip_params
    #   params.fetch(:trip, {})
    # end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_trip.html.erb
<div id="<%= dom_id trip %>">
</div>

app/views/trips/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Trips</h1>

<h2>Current_time: <%= DateTime.now.localtime %></h2>

<%= form_tag trips_path, :method => 'get' do %>
  <p>
    <%= select_tag :departure, options_from_collection_for_select(Location.all, :id, :name),
                   {:class=>'form-control', :prompt => 'Select departure'}  %>
    <%= select_tag :arrival, options_from_collection_for_select(Location.all, :id, :name),
                   {:class=>'form-control', :prompt => 'Select arrival'}  %>
    <%= datetime_field_tag :departure_time %>

    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
  <tr>
    <th>Departure</th>
    <th>Arrival</th>
    <th>Departure time</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @trips.each do |trip| %>
    <tr>
      <td><%= trip.departure.name %></td>
      <td><%= trip.arrival.name %></td>
      <td><%= trip.departure_time.localtime %></td>
      <td><%= link_to 'Book', book_trip_path(trip) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/trips/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @trip %>

<div>
  <%= link_to "Edit this trip", edit_trip_path(@trip) %> |
  <%= link_to "Back to trips", trips_path %>

  <%= button_to "Destroy this trip", @trip, method: :delete %>
</div>