config/routes.rb
Rails.application.routes.draw do
  resources :passengers, only: [:index]

  resources :trips, only: [:index] do
    resources :passengers
    member do
      get :book
    end
  end


  resources :user do
    resources :passengers, only: [:show] do
      member do
        get :add_extra_luggage
      end
    end
    resources :credit_cards
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #

  # Defines the root path route ("/")
  root "trips#index"
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user

  validates_presence_of :cardholder, :number, :cvv, :expire_date
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: %i[ show edit update destroy ]

  # GET /credit_cards or /credit_cards.json
  def index
    @credit_cards = current_user.credit_cards
  end

  # GET /credit_cards/1 or /credit_cards/1.json
  def show
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # GET /credit_cards/1/edit
  def edit
  end

  # POST /credit_cards or /credit_cards.json
  def create
    @credit_card = current_user.credit_cards.build(credit_card_params)

    if @credit_card.save
      redirect_to user_credit_card_url(current_user, @credit_card), notice: "Credit card was successfully created."
    end
  end

  # PATCH/PUT /credit_cards/1 or /credit_cards/1.json
  def update
    respond_to do |format|
      if @credit_card.update(credit_card_params)
        format.html { redirect_to user_credit_card_url(current_user, @credit_card), notice: "Credit card was successfully updated." }
        format.json { render :show, status: :ok, location: @credit_card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1 or /credit_cards/1.json
  def destroy
    @credit_card.destroy

    respond_to do |format|
      format.html { redirect_to credit_cards_url, notice: "Credit card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_credit_card
    @credit_card = CreditCard.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def credit_card_params
    params.require(:credit_card).permit( :user, :cardholder, :number, :cvv, :expire_date)
  end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_credit_card.html.erb
<div id="<%= dom_id credit_card %>">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>credit_card id:</strong>
    <%= credit_card.id %>
  </p>

  <p>
    <strong>Cardholder:</strong>
    <%= credit_card.cardholder %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= credit_card.number %>
  </p>

  <p>
    <strong>Cvv:</strong>
    <%= credit_card.cvv %>
  </p>

  <p>
    <strong>Expired date:</strong>
    <%= credit_card.expire_date %>
  </p>
</div>

app/views/credit_cards/_form.html.erb
<%= form_with(model: [current_user, credit_card], local: true) do |form| %>
  <% if credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
        <% credit_card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cardholder %>
    <%= form.text_field :cardholder %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :cvv %>
    <%= form.text_field :cvv %>
  </div>

  <div class="field">
    <%= form.label :expire_date %>
    <%= form.text_field :expire_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Editing credit card</h1>

<%= render "form", credit_card: @credit_card %>

<br>

<div>
  <%= link_to "Show this credit card", user_credit_card_path(current_user, @credit_card) %> |
  <%= link_to "Back to credit cards", user_credit_cards_path(current_user) %>
</div>

app/views/credit_cards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Credit cards</h1>

<div id="credit_cards">
  <% @credit_cards.each do |credit_card| %>
    <%= render credit_card %>
    <p>
      <%= link_to "Show this credit card", user_credit_card_path(current_user, credit_card) %>
    </p>
  <% end %>
</div>

<%= link_to "New credit card", new_user_credit_card_path(current_user) %>

app/views/credit_cards/new.html.erb
<h1>New credit card</h1>

<%= render "form", credit_card: @credit_card %>

<br>

<div>
  <%= link_to "Back to credit cards", user_credit_cards_path(current_user) %>
</div>

app/views/credit_cards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @credit_card %>

<div>
  <%= link_to "Edit this credit card", edit_user_credit_card_path(current_user, @credit_card) %> |
  <%= link_to "Back to credit cards", user_credit_cards_path(current_user) %>

  <% if session[:trip_id] %>
    <%= link_to_if session[:trip_id], 'Book your trip', book_trip_path(session[:trip_id]) %>
  <% end %>

  <%= button_to 'Destroy credit card', [current_user, @credit_card], method: :delete %>
</div>