config/routes.rb
Rails.application.routes.draw do
  resources :passengers, only: [:index]

  resources :trips, only: [:index] do
    resources :passengers
    member do
      get :book
    end
  end


  resources :user do
    resources :passengers, only: [:show] do
      member do
        get :add_extra_luggage
      end
    end
    resources :credit_cards
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #

  # Defines the root path route ("/")
  root "trips#index"
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :user
  belongs_to :trip

  validate :free_seats?, :payment_info?, :max_extra_luggage?
  before_destroy :enough_time_to_refund?

  def free_seats?
    if self.trip.passengers.count >= self.trip.seats
      errors.add(:no_seats, "Sorry, this trip already full")
    end
  end

  def payment_info?
    if self.user.credit_cards.empty?
      errors.add(:no_credit_card, "You must provide payment information before")
    end
  end

  def enough_time_to_refund?
    if DateTime.now > self.trip.departure_time - 30.minutes
      errors.add(:refund_time_expired, "Refund allow before 30 minutes from departure time")
      throw :abort
    end
  end

  def max_extra_luggage?
    if self.extra_luggage > 6
      errors.add(:refund_time_expired, "The bus is full of luggage")
    end
  end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: %i[ show add_extra_luggage destroy ]

  before_action :verify_if_admin, only: %i[ index ]
  before_action :authenticate_user!, :only => [:index]

  # GET /passengers or /passengers.json
  def index
    @total_revenue_by_departure = Trip.total_revenue_by_departure
    @total_revenue = Passenger.sum :price
  end

  # GET /passengers/1 or /passengers/1.json
  def show
  end

  def add_extra_luggage
    @passenger.extra_luggage += params[:extra_luggage].to_i if params[:extra_luggage].try(:to_i).is_a? Integer
    @passenger.price += 5.00

    if @passenger.save
      redirect_to user_passenger_path(current_user, @passenger), notice: "Extra luggage add to your trip"
    else
      redirect_to user_passenger_path(current_user, @passenger), notice: @passenger.errors.messages.values
    end
  end

  # DELETE /passengers/1 or /passengers/1.json
  def destroy
    if @passenger.destroy
      redirect_to root_path, notice: "Ticket was refund"
    else
      redirect_to root_path, notice: @passenger.errors.messages.values
    end
  end

  private

    # todo: use pundit for authorization
    def verify_if_admin
      redirect_to root_path, notice: "you are no able to see this page" unless current_user.admin?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def passenger_params
      params.require(:passenger).permit(:extra_luggage)
    end
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/passengers/_passenger.html.erb
<div id="<%= dom_id passenger %>">


  <p>
    <strong>Passenger id:</strong>
    <%= @passenger.id %>
  </p>

  <p>
    <strong>email:</strong>
    <%= @passenger.user.email %>
  </p>

  <p>
    <strong>Departure:</strong>
    <%= @passenger.trip.departure.name.capitalize %>
  </p>

  <p>
    <strong>Arrival:</strong>
    <%= @passenger.trip.arrival.name.capitalize %>
  </p>

  <p>
    <strong>Departure time:</strong>
    <%= @passenger.trip.departure_time %>
  </p>

  <p>
    <strong>Extra luggage bought:</strong>
    <%= @passenger.extra_luggage %>
  </p>

</div>

app/views/passengers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Revenues</h1>

<div id="passengers">
  <% @total_revenue_by_departure.to_a.each do |passenger| %>

    <p>
      <%= passenger.first.name %>
      <%= passenger.last %> eur
    </p>
    <p>
      <%# link_to "Show this passenger", passenger %>
    </p>
  <% end %>

  <p>
    Total revenue
    <%= @total_revenue %>
  </p>

</div>

app/views/passengers/show.html.erb
<p style="color: green"><%# notice %></p>

<%= render @passenger %>

<div>

  <%= form_tag add_extra_luggage_user_passenger_path(current_user, @passenger), :method => 'get' do %>
    <p>
      <%= number_field_tag 'extra_luggage', 1, max: 2, min: 1  %>

      <%= submit_tag "Add luggage", :name => nil %>
    </p>
  <% end %>
  <br>

  <%= link_to "Back to Trips", trips_path %>

  <%= button_to 'Refund ticket', [@passenger.trip, @passenger], method: :delete %>
</div>